# Generated by Django 5.2.7 on 2025-10-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_App_Code', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZAR', 'South African Rand'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi'), ('NGN', 'Nigerian Naira')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZAR', 'South African Rand'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi'), ('NGN', 'Nigerian Naira')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZAR', 'South African Rand'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi'), ('NGN', 'Nigerian Naira')], default='USD', max_length=3),
        ),
    ]
